name: Compile LaTeX PDF
 
 on:
   push:
     branches:
       - main  # Trigger on push to the 'main' branch
 
 jobs:
   build:
     runs-on: ubuntu-latest  # Use Ubuntu as the environment
 
     steps:
     - name: Checkout repository
       uses: actions/checkout@v2
 
     - name: Set up TeX Live (full installation)
       run: |
         sudo apt-get update
         sudo apt-get install -y texlive-full  # Install the full TeX Live distribution
 
     - name: Compile LaTeX document
       run: |
         pdflatex -interaction=nonstopmode main.tex || exit 1  # Compile LaTeX
         pdflatex -interaction=nonstopmode main.tex || exit 1  # Compile twice for proper references
 
     - name: Upload PDF as artifact
       uses: actions/upload-artifact@v3
       uses: actions/upload-artifact@v4
       with:
         name: compiled-pdf
         path: main.pdf  # Path to the compiled PDF (in the root directory)
